### ISSUE TITLE
Coming Back to the Downloading datas Issue

### ISSUE THREAD

**Issue by Momo69100** [ropensci/yfR#15]
Hello, first i want to say that i really do appreciate your work.
I allready saw all the topics about this issue.
But there is no possibilities to extend the download limit?
like it was befor with getbatchsymbol?
It was so convenient working with big data but now impossible to work.
Waiting for your answer, thanks in advance

**Comment by msperlin** [comment]
Hi Momo, 

Yes, there is a workaround using the json api, but it depends on the version 0.4.20.2 of quantmod, which is not yet on cran. 

As soon as it hits CRAN, I'll upload my new version.

**Comment by msperlin** [comment]
I'll leave this issue open until then..

**Comment by msperlin** [comment]
I'm still waiting for version 0.4.20.2 of quantmod on CRAN. 
Nonetheless, I've been using yfR without parallel computations and it works great, even for large data.

**Comment by msperlin** [comment]
No update from quantmod so far. Nonetheless, I've been using yfR without parallel download and it works fine. If you are needing constant updates of large batches, perhaps the best way is to sign up for a paid service.

I'm going to close this issue as there is not much I can do.
