### ISSUE TITLE
Suggestion: remove/change curl::has_internet() from yfR

### ISSUE THREAD

**Issue by jtrecenti** [ropensci/yfR#20]
Hi! Thanks for this awesome package. We use it a lot in our classes at Insper.

We are facing some issues running `yfR::yf_get()` because `curl::has_internet()` returns `FALSE`, even though we have a stable internet connection here. Probably it is some proxy issue that we do not control.

A suggestion would be to remove this check (if the user does not have internet connection, the download will fail anyway) or add a `check_internet=` parameter having `TRUE` as default.

What do you think? Thanks!

**Comment by msperlin** [comment]
Hi Julio,

I think it is best to add a option as argument (check_internet). You would be surprised how many emails I get when people try to use the package without internet. 

Btw, can you test `pingr::is_online()`, which seems to use another method. Let me know how it goes..

**Comment by jtrecenti** [comment]
Thanks for the answer!

`pingr::is_online()` works as expected here at Insper.

``` r
pingr::is_online()
#> [1] TRUE
```

<sup>Created on 2022-11-11 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

Do you prefer to 

1) change `{curl::has_internet()}` -> `{pingr::is_online()}` (more 📦 dependencies) or 
2) add a parameter (more parameters 😅)? 

I'd be happy to make a PR

**Comment by jtrecenti** [comment]
Another option is to use this test (used by `testthat`) instead of `curl::has_internet()`

```r
> testthat::skip_if_offline
function (host = "r-project.org") 
{
    skip_on_cran()
    skip_if_not_installed("curl")
    has_internet <- !is.null(curl::nslookup(host, error = FALSE))
    if (!has_internet) {
        skip("offline")
    }
}
```

This one also works here. This way there's no need to add any new dependencies.

**Comment by msperlin** [comment]
> Thanks for the answer!
> 
> `pingr::is_online()` works as expected here at Insper.
> 
> ```r
> pingr::is_online()
> #> [1] TRUE
> ```
> 
> Created on 2022-11-11 with [reprex v2.0.2](https://reprex.tidyverse.org)
> 
> Do you prefer to
> 
> 1. change `curl::has_internet()` -> `pingr::is_online()` (more package dependencies) or
> 2. add a parameter (more parameters sweat_smile)?
> 
> I'd be happy to make a PR

Using pingr is alright, it is a minimal package. 

Sure, fell free to send a PR. Otherwise I'll fix the code next week.
