### ISSUE TITLE
`'all_of' is not an exported object` if tidyr version < 1.2.0

### ISSUE THREAD

**Issue by ccsarapas** [ropensci/yfR#22]
Per [this SO thread](https://stackoverflow.com/questions/74552117/yf-convert-to-wide-command-from-yfr-package-not-working-in-r/), `yf_convert_to_wide()` throws an error for users running older versions of tidyr. I suspect this is because the function source calls `tidyr::all_of()`, but `all_of()` originates in the tidyselect package and wasn't re-exported by tidyr until v1.2.0. I would consider either changing `tidyr::all_of()` to `tidyselect::all_of()`, or adding `tidyr (>= 1.2.0)` to the DESCRIPTION file.

**Comment by msperlin** [comment]
Thanks, I'm fixing it right now.

**Comment by msperlin** [comment]
now using tidyselect
