### ISSUE TITLE
Downloading maximum range of data without knowing before hand what the maximum range is

### ISSUE THREAD

**Issue by cemal95** [ropensci/yfR#27]
I tried downloading a stock from a selection of stocks, in order to obtain all the possible observations I put the first_date = "1920-01-01". However this not work. Is there a way to do this?

![Screenshot 2024-11-13 at 20 37 49](https://github.com/user-attachments/assets/3ab0ed74-fd9f-4f7d-a3f9-6dacb91bfded)

So implementing larger scale analysis cannot be automated as every historic range needs to be know before hand. Using yahoo finance python API does work like that. Is there a way to solve this?

**Comment by msperlin** [comment]
Unfortinately, there is no way of telling the first available date beforehand. But, you can set thresh_bad_data = 0 and the funtion will always return any data it finds..

**Comment by cemal95** [comment]
> return any data it finds..

It worked, thank you!
