### ISSUE TITLE
Ignoring errors and saving ticker on the side

### ISSUE THREAD

**Issue by cemal95** [ropensci/yfR#28]
Coming back to the automization process, how can catch these errors and save them to a separate list of the ones that did not work. It has to do with the name of the ticker, but I cant filter 2000+ tickers so I would like to catch errors and save in a list called error_list.

Error in yf_get(tickers = tick, first_date = "1920-01-01", last_date = "2024-11-13",  : 
  Resulting data has 0 rows.. Are your tickers and date ranges correct? Search your ticker at <https://finance.yahoo.com/

**Comment by cemal95** [comment]
https://stackoverflow.com/a/59462794/11819467

**Comment by msperlin** [comment]
The package already does that. In the output objec, there is an attribute called df_control:

![image](https://github.com/user-attachments/assets/4a5e1b81-8a11-491a-bf95-3f14e8355bbf)

There you'll find a dataframe with details of the importation process.

**Comment by cemal95** [comment]
I see, bit I think the question is already answered using the threshold arguement. On a side note, can you convert the OHLC data into quarterly data using monthly data?

**Comment by msperlin** [comment]
> I see, bit I think the question is already answered using the threshold arguement. On a side note, can you convert the OHLC data into quarterly data using monthly data?

Sure, but it  sounds too specific to implement in the package. Nonetheless, you can always write a custom function and, based on daily/monthly data, aggregate for quarters.
